-- reader_menu_order.lua — KOReader 阅读界面菜单定制（用户选择版）
-- 位置: /mnt/us/koreader/settings/reader_menu_order.lua
-- 机制: 完整覆盖默认编排; 列入 KOMenu:disabled 的项被隐藏;
--       被禁的分组(更多工具/帮助)整组定义删除且成员全部进 disabled, 防止孤儿项。
-- 用户选择(2026-08-18):
--   ④ 工具: 只保留 进度同步(kosync)，其余全藏(含"更多工具"整组)
--   ⑤ 搜索: 藏 字典/维基/翻译/Calibre找书，保留 搜索设置/全文搜索/书签搜索
--   ⑥ 主菜单: 藏 OTA更新、帮助(整组)
local Device = require("device")

local order = {
    ["KOMenu:menu_buttons"] = {
        "navi",
        "typeset",
        "setting",
        "tools",
        "search",
        "filemanager",
        "main",
    },
    navi = {
        "table_of_contents",
        "bookmarks",
        "toggle_bookmark",
        "bookmark_browsing_mode",
        "navi_settings",
        "----------------------------",
        "hide_nonlinear_flows",
        "----------------------------",
        "book_map",
        "page_browser",
        "----------------------------",
        "go_to",
        "skim_to",
        "autoturn",
        "----------------------------",
        "go_to_previous_location",
        "go_to_next_location",
    },
    navi_settings = {
        "toc_ticks_level_ignore",
        "----------------------------",
        "toc_items_per_page",
        "toc_items_font_size",
        "toc_items_show_chapter_length",
        "toc_items_with_dots",
        "----------------------------",
        "toc_alt_toc",
        "----------------------------",
        "handmade_toc",
        "handmade_hidden_flows",
        "handmade_settings",
        "----------------------------",
        "page_map",
        "bookmarks_settings",
    },
    typeset = {
        "document_settings",
        "----------------------------",
        "set_render_style",
        "style_tweaks",
        "----------------------------",
        "change_font",
        "typography",
        "----------------------------",
        "switch_zoom_mode",
        "----------------------------",
        "page_overlap",
        "speed_reading_module_perception_expander",
        "----------------------------",
        "highlight_options",
        "selection_text",
        "panel_zoom_options",
        "djvu_render_mode",
        "start_content_selection",
    },
    setting = {
        "frontlight",
        "night_mode",
        "----------------------------",
        "network",
        "screen",
        "----------------------------",
        "taps_and_gestures",
        "navigation",
        "document",
        "----------------------------",
        "language",
        "device",
        "----------------------------",
        "status_bar",
    },
    document = {
        "document_metadata_location",
        "document_auto_save",
        "document_metadata_arc",
        "document_end_action",
        "language_support",
        "----------------------------",
        "partial_rerendering",
    },
    device = {
        "keyboard_layout",
        "external_keyboard",
        "font_ui_fallbacks",
        "----------------------------",
        "time",
        "units",
        "device_status_alarm",
        "charging_led",
        "autostandby",
        "autosuspend",
        "autoshutdown",
        "pageturn_power",
        "ignore_sleepcover",
        "ignore_open_sleepcover",
        "cover_events",
        "ignore_battery_optimizations",
        "mass_storage_settings",
        "file_ext_assoc",
        "screenshot",
    },
    navigation = {
        "back_to_exit",
        "back_in_filemanager",
        "back_in_reader",
        "backspace_as_back",
        "----------------------------",
        "physical_buttons_setup",
        "----------------------------",
        "android_volume_keys",
        "android_haptic_feedback",
        "android_back_button",
        "----------------------------",
        "opening_page_location_stack",
        "skim_dialog_position",
    },
    network = {
        "network_wifi",
        "network_proxy",
        "network_powersave",
        "network_restore",
        "network_info",
        "network_before_wifi_action",
        "network_after_wifi_action",
        "network_dismiss_scan",
        "----------------------------",
        "ssh",
    },
    screen = {
        "screensaver",
        "coverimage",
        "autodim",
        "----------------------------",
        "screen_rotation",
        "----------------------------",
        "screen_dpi",
        "screen_eink_opt",
        "autowarmth",
        "color_rendering",
        "----------------------------",
        "screen_timeout",
        "fullscreen",
        "----------------------------",
        "screen_notification",
    },
    taps_and_gestures = {
        "gesture_manager",
        "gesture_overview",
        "gesture_intervals",
        "----------------------------",
        "ignore_hold_corners",
        "screen_disable_double_tap",
        "----------------------------",
        "follow_links",
        "----------------------------",
        "menu_activate",
        "page_turns",
        "scrolling",
        "long_press",
    },
    tools = {
        "progress_sync",
    },
    search = {
        "search_settings",
        "----------------------------",
        "fulltext_search",
        "fulltext_search_findall_results",
        "bookmark_search",
    },
    search_settings = {
        "dictionary_settings",
        "wikipedia_settings",
        "translation_settings",
        "----------------------------",
        "fulltext_search_settings",
    },
    filemanager = {},
    main = {
        "history",
        "open_previous_document",
        "----------------------------",
        "favorites",
        "collections",
        "bookmark_browser",
        "----------------------------",
        "book_status",
        "book_info",
        "----------------------------",
        "mass_storage_actions",
        "----------------------------",
        "exit_menu",
    },
    exit_menu = {
        "restart_koreader",
        "----------------------------",
        "sleep",
        "poweroff",
        "reboot",
        "----------------------------",
        "start_bq",
        "exit",
    },
    -- 隐藏清单
    ["KOMenu:disabled"] = {
        -- ④ 工具(保留 progress_sync)
        "read_timer",
        "calibre",
        "exporter",
        "statistics",
        "cloudstorage",
        "move_to_archive",
        "wallabag",
        "news_downloader",
        "text_editor",
        "profiles",
        "qrclipboard",
        "more_tools",
        -- 更多工具的成员(整组隐藏, 防孤儿项)
        "auto_frontlight",
        "battery_statistics",
        "book_shortcuts",
        "synchronize_time",
        "keep_alive",
        "doc_setting_tweak",
        "terminal",
        "plugin_management",
        "patch_management",
        -- ⑤ 搜索(保留 搜索设置/全文搜索/书签搜索)
        "dictionary_lookup",
        "dictionary_lookup_history",
        "vocabbuilder",
        "wikipedia_lookup",
        "wikipedia_history",
        "translate_current_page",
        "find_book_in_calibre_catalog",
        -- ⑥ 主菜单
        "ota_update",
        "help",
        -- 帮助的成员(整组隐藏, 防孤儿项)
        "quickstart_guide",
        "search_menu",
        "report_bug",
        "plugins_disable_external",
        "system_statistics",
        "version",
        "about",
        -- 运行时注册的孤儿项(sorting_hint=more_tools, 组已隐藏, 不收编会崩菜单)
        "hello_world",
        "httpremote",
    },
}

if not Device:hasExitOptions() then
    order.exit_menu = nil
end

return order
